### ISSUE TITLE
Allow advanced config of WiFi module

### ISSUE THREAD

**Issue by bjpirt** [bjpirt/mirobot-ui#11]
It would be good to be able to configure some of the more advanced parameters of the WiFi module, including:
 - SSID
 - Channel
 - WiFi password and encryption
 - web page password

**Comment by jjsanderson** [comment]
For reference: my finicky university wifi (which also causes problems with Raspberry Pi wifi modules) requires:

* WPA & WPA2 Enterprise
* Protected EAP
* CA Certificate: none
* PEAP version: automatic
* Inner authentication: MSCHAPv2

I'll confess to ignorance on much of that. Some of it may require hardware capabilities which are beyond Mirobot. In practice, we usually use it with a 4G phone as a mobile hotspot and bypass the university wifi entirely.

**Comment by bjpirt** [comment]
I'm pretty sure the WiFi module isn't going to be able to support that I'm afraid, the 4G approach is a good one. Alternatively you might just be able to get a router and plug it into a Ethernet port and then just setup a local WiFi network just for the bots.

**Comment by jjsanderson** [comment]
I thought as much. No worries, though the problem with 4G dongles and phones is that network operators seem to limit them to 10 connected devices (or even fewer - with some networks it's three devices). I'll update if school wifi networks cause problems.

Plugging an access point into the wired network here results in a SWAT team of IT technicians bursting through the windows and a painfully loud voice shouting "PUT THE ROBOT DOWN AND STEP AWAY FROM THE ROUTER". I have a separate ticket raised about this.

**Comment by bjpirt** [comment]
I've just pushed an update to the UI which adds support for more advanced configuration of the WiFi
