### ISSUE TITLE
Wifo Module Documentation

### ISSUE THREAD

**Issue by crami** [bjpirt/mirobot-ui#12]
Hi 

Do you have some more documentation on the Wifi module ? Whats is available for download at http://en.usr.cn/Tiny-size-low-power-uart-ttl-to-802.11b-g-n-low-price-wifi-module is very limmited.

Regards

  Matthias

**Comment by silps** [comment]
yesterday they added the webpage sources http://www.usriot.com/Download/196.html ^_^

**Comment by bjpirt** [comment]
That's good to see - thanks for that. This is what I had been working from to develop UI, although there are a bunch of oddities that aren't documented anywhere, like the config pages seemingly needing to have their file names hardcoded :-( Makes it quite inflexible, but hey...

**Comment by silps** [comment]
Some of the documentation about the param names and file names which is included in the download above ^_^
