### ISSUE TITLE
Support SSID name with quotes

### ISSUE THREAD

**Issue by automata** [bjpirt/mirobot-ui#17]
I have a not so common SSID name. I really appreciate ASCII art, so my SSID name is `-._.-'"'-._.-'"'-._.-   ><(((">` a little :fish:. The first time I configured the wifi using `mirobot-ui`, the scan button didn't works so I tried manual configuration. Now, my SSID is set on `mirobot-ui`, but the JS file shows an error regarding bad format for the SSID variable. That's because the quotes aren't escaped appropriately. Something like `'foo"bar'.replace(/\"/g, "\\\"");` could fix that.

I tried to update the `mirobot-ui` using a bin file but the SSID variable doesn't changes. Any way to set the variable manually or to force a reset?

**Comment by bjpirt** [comment]
I'm going to close this because unfortunately there's nothing I can do about it. I'm currently looking at a switch of WiFi modules so I will have more control over the firmware in that part.
