### ISSUE TITLE
Collision avoidance/line following not working

### ISSUE THREAD

**Issue by NickCole1953** [bjpirt/mirobot-ui#22]
Ben,

Could you point me in the direction of a simple 'howto' document on updating the Arduino code and getting the collision avoidance etc.

Thanks, 

Nick Cole

**Comment by bjpirt** [comment]
Have you already tried updating using the updater?

http://mirobot.io/build/firmware_update/

Although I've found that a little unreliable for my liking so have been considering recommending just using a USB -> Serial converter to update the Arduino directly, like on this page:

http://mirobot.io/build/firmware/

If you wouldn't mind, could you ask any more questions over on the Mirobot Google Group (https://groups.google.com/forum/?pli=1#!forum/mirobot), that way others can find the answers more easily.
Cheers,
Ben
