### ISSUE TITLE
remote control mode

### ISSUE THREAD

**Issue by forresto** [bjpirt/mirobot-ui#6]
Some way to send signals to the bot directly. Perhaps there could be buttons to the left of each item in the block library. Would be nice as a first-boot test.

Maybe some people would like drawing like that, in real time. If this is another mode, there could be a history list of commands sent to the bot, so it could replay a list of commands.

**Comment by bjpirt** [comment]
Closing this PR now that we have:

http://apps.mirobot.io/remote/
