### ISSUE TITLE
"show password" security hole?

### ISSUE THREAD

**Issue by forresto** [bjpirt/mirobot-ui#7]
Is it a security hole to have the mirobot network (open) have the config for my private network with "show password?"

**Comment by bjpirt** [comment]
I've just pushed an update which should allow you to join your network more securely. You can now enable encryption on the built-in access point so when you configure it to join your network it will no longer be on an unencrypted connection.

I've also removed the "show password" feature, though still need to make it not send the password out and then only send it if it has changed.
