### ISSUE TITLE
Investigate using Blockly

### ISSUE THREAD

**Issue by forresto** [bjpirt/mirobot-ui#8]
Active development at Google, https://code.google.com/p/blockly/

We could probably just use most of this demo; has #4 and #5 covered: https://blockly-demo.appspot.com/static/apps/turtle/index.html#j9axws

**Comment by silps** [comment]
Hey guys, I also tried to minify Blockly and push it to the WiFi module. I got problems already above 250KB, the content just stopped loading. I ended up extending the Mirobot UI and using that. I am also interested to hack on this further in the future. To run Blockly on a device itself would be a awesome way to program things.

Thx Ben for all the great work you have done with Mirobot ^_^

**Comment by bjpirt** [comment]
Have you checked out http://apps.mirobot.io yet? I got blockly running pretty nicely there as well as a few other apps.

**Comment by silps** [comment]
Yes I saw those very nice apps ^_^
It would still be very interesting to get it working locally on the module. Also for other embedded applications. In Mirobot case it is nice to have during workshops which are conducted in places where there is no Internet and computers, may be even no power :)

**Comment by bjpirt** [comment]
When I'm in that situation (e.g. maker faires, etc) I tend to:
 - join the mirobot access point
 - run the apps as a local server
 - configure the apps to point to 10.10.100.254

which has worked pretty well so far. I regularly do this with no power or internet. Hope that helps.

**Comment by silps** [comment]
that is a good point actually ^_^
